### ISSUE TITLE
ReferenceError: Velocity is not defined

### ISSUE THREAD

**Issue by lukos** [WhatSock/apex#63]
I am using the drag and drop and although it generally works, if I try and access it via the keyboard, I see the following error:

```
ReferenceError: Velocity is not defined
    at HTMLUListElement.onRender (Drag.js:283:23)
    at DCR4 (4X.js:3962:35)
    at Function.<anonymous> (4X.js:419:15)
    at Function.loop (4X.js:791:16)
    at cont (4X.js:416:14)
    at Function._parseDCScripts (4X.js:434:14)
    at DCR3 (4X.js:3745:16)
    at DCR2 (4X.js:3595:20)
    at Function.<anonymous> (4X.js:419:15)
    at Function.loop (4X.js:791:16)
```

Despite the fact that I do have VelocityUI.js linked and it is loading.

The ordering I have for the imports is this:

```
<script src="/content/js/4x/VelocityUI.js" type="text/javascript" asp-append-version="true"></script>
<script src="/content/js/4x/Animate.js" type="text/javascript" asp-append-version="true"></script>
<script src="/content/js/4x/AccName.js" type="text/javascript" asp-append-version="true"></script>
<script src="/content/js/4x/RovingTabIndex.js" type="text/javascript" asp-append-version="true"></script>
<script src="/content/js/4x/Menu.js" type="text/javascript" asp-append-version="true"></script>
<script src="/content/js/4x/Dragula.js" type="text/javascript" asp-append-version="true"></script>
<script src="/content/js/4x/Drag.js" type="text/javascript" asp-append-version="true"></script>
```

The only thing is that velocity seems to have a load of stuff at the top for commonjs and AMD so I don't know if I need to do anything to get it to load as a normal global. I also tried with the latest one from the Velocityjs.org site but it does the same thing.

**Comment by accdc** [comment]
Hi,
I understand the confusion. Velocity has 2 js files and not just 1. Both of these are included in the repo and are listed in the new dependency lists.

Velocity.js has to be loaded before VelocityUI.js. The first is the core functionality and the second includes many animation presets that depend on the core.

So your list should look like this instead.

```
<script src="/content/js/4x/Velocity.js" type="text/javascript" asp-append-version="true"></script>
<script src="/content/js/4x/VelocityUI.js" type="text/javascript" asp-append-version="true"></script>
<script src="/content/js/4x/Animate.js" type="text/javascript" asp-append-version="true"></script>
<script src="/content/js/4x/AccName.js" type="text/javascript" asp-append-version="true"></script>
<script src="/content/js/4x/RovingTabIndex.js" type="text/javascript" asp-append-version="true"></script>
<script src="/content/js/4x/Menu.js" type="text/javascript" asp-append-version="true"></script>
<script src="/content/js/4x/Dragula.js" type="text/javascript" asp-append-version="true"></script>
<script src="/content/js/4x/Drag.js" type="text/javascript" asp-append-version="true"></script>
```

Doing this should resolve your error.

**Comment by lukos** [comment]
Hi @accdc and thanks for the reply. I did originally include velocity.js and it didn't work then. I removed it because it says it is a shim only needed if jquery is not loaded but I have loaded jquery so don't need the shim. Anyhow, it doesn't work either way (same error).

Thanks again

**Comment by accdc** [comment]
That is very strange, what is the environment you are using to run the code in?

I'm running the same modules here and not seeing any errors.
https://whatsock.com/Templates/Drag/Move/index.htm

**Comment by accdc** [comment]
Ah, I know what the issue is. I'll make a fix for it today and get back.

**Comment by accdc** [comment]
Okay, I just pushed an update. You will need to update the modules listed in the most recent commit to ensure the latest code is being used. The issue was that "Velocity(" was not always explicitly referencing "window." which worked outside of encapsulated code environs but not always within.

If using NPM install you can use "npm install apex4x" to get the latest code.

Below is the list of modified files in the fix commit.

Changed paths:
M 4X/Min/Animate.js
M 4X/Min/Drag.js
M 4X/Min/Straylight.js
M 4X/Modules/Animate.js
M 4X/Modules/Drag.js
M 4X/Modules/Straylight.js
M 4X/Standard/Min/Animate.js
M 4X/Standard/Min/Drag.js
M 4X/Standard/Min/Straylight.js
M 4X/Standard/Modules/Animate.js
M 4X/Standard/Modules/Drag.js
M 4X/Standard/Modules/Straylight.js
M Bundle/4X.js
M package.json

Log Message:
-----------
Corrected an issue where Velocity whas not being correctly called from window.

**Comment by accdc** [comment]
Hi, unfortunately I didn't realize until recently that I didn't include the updated files within the 4X/Standard/Modules folder as needed to fix your issue. I fixed this and pushed the code recently so it should correct the problem. If you could please retest and get back that would be great. 
All the best,
Bryan

**Comment by lukos** [comment]
Also, you mention `4X.js` in Bundle directory in the changed files lists but not 4X.js under the 4X directory. Is that correct?

**Comment by accdc** [comment]
Actually all of them should be synchronized. Are you still not using Velocity.js? I had to make a change in both of those at `4X/Modules/Velocity.js` and `4X/Standard/Modules/Velocity.js` which you can see at the end of the file where it has the following:

```
$A.extend({
  Velocity: window["Velocity"],
});
```

When the project is built, it updates the file at `Bundle/4X.js` automatically by pulling in the changes referenced in the BuildBundle.js file so these changes should be encorporated.

Can you confirm that your version of Velocity.js has the code block above in it at the end? Or if using the Bundle version that you are running the most recent build version?

**Comment by lukos** [comment]
Hi Brian. I have now included `Velocity.js` which does include that code but I still get the same error. My confusion was the comment at the top of the file which I read to mean that we didn't need `Velocity.js` if we already had full jQuery but I now realised it only applies to the shims at the top and not the whole file.

I am currently using 4X.js from the 4X directory because I currently want the unminified version, that's why I wondered why it wasn't mentioned as changed (although I did update it from the latest npm files). That's why I just wondered if the update to that particular file might have been missed. I tried to use the one under Bundle but that obviously doesn't work with the standard module js files.

**Comment by accdc** [comment]
I'm trying to track down where this issue is occurring.

Can you run a test for me using the latest code repo for Apex 4X?

In the root folder, run WebserverInstall.sh to install the local webserver, then WebserverRun.sh to run index.htm in the localhost.

Click the Test button to run the tooltip example you see there.

You should see the tooltip render using the $A.Velocity animation effect shown in the code edit field.

This is using the bundle, but it is compiled using all the unminified module files within the 4X folder.

Do you see the same error in your console?

Thanks,
Bryan

**Comment by lukos** [comment]
That works OK. It beeps and puts up "Wow" over the button at the top and there are no console errors.

**Comment by accdc** [comment]
Thanks, the confusing thing is that test page pulls in the same code that you are referencing if you are using the same files from that repo since the bundle is compiled using the same unminified files.

Is it possible there is a server-side caching issue within the platform you are using?

**Comment by lukos** [comment]
Hi Bryan, I put a breakpoint in the velocity.js file and found that where it is extending 4x with `window["Velocity"]`, that is undefined so it isn't added to 4x, hence the later error.

It does call the code that builds Velocity but I am not sure where it is supposed to be added to the window or whether that should work just because it is a global.

**Comment by accdc** [comment]
Arg, I think I may know what's happening. Are you running jQuery in your project? If yes and you load jQuery before Velocity.js then it will ignore the code that loads window.Velocity. 

You can test this by loading jQuery after Velocity.js or change the code at the end of Velocity.js from:

```
$A.extend({
  Velocity: window["Velocity"],
});
```

To this instead:

```
$A.extend({
  Velocity: $["Velocity"],
});
```

Please let me know if this works and I'll add logic to check for this in an a new update to the repo.

**Comment by lukos** [comment]
Yes I am using jQuery, yes, I include it before and yes, your suggested change works. Presumably that just means you can add a test in the registration `if typeof(jquery["Velocity"]) !== "undefined") register as jquery else register with window`?

Thanks so much

**Comment by accdc** [comment]
Excellent, can you try this to see if the fix will work?

At the end of Velocity.js, replace what is there with the following instead.

```
$A.extend({
  Velocity: (window.jQuery ? window.jQuery : window)["Velocity"],
});
```

If this works for you I'll add it to the general repo.

**Comment by lukos** [comment]
Hi Bryan, yes that works, thanks.
